# Generated by Django 3.1.4 on 2020-12-26 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ConnectionApp', '0002_auto_20201226_1027'),
    ]

    operations = [
        migrations.DeleteModel(
            name='validation',
        ),
        migrations.AddField(
            model_name='familyidentity',
            name='verified',
            field=models.BooleanField(default=False),
        ),
    ]
