# Generated by Django 3.1.4 on 2020-12-30 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ConnectionApp', '0004_auto_20201228_1313'),
    ]

    operations = [
        migrations.AddField(
            model_name='familyidentity',
            name='verified',
            field=models.BooleanField(default=False),
        ),
    ]
