# Generated by Django 3.1.7 on 2021-03-15 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ConnectionApp', '0005_familyidentity_verified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='familyidentity',
            name='firstName',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='familyidentity',
            name='lastName',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='familyidentity',
            name='middleName',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
