# Generated by Django 3.2.3 on 2021-06-30 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ConnectionApp', '0006_auto_20210315_1214'),
    ]

    operations = [
        migrations.AddField(
            model_name='familyidentity',
            name='national_doc',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='familyidentity',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
